version: "3.7"

x-logging: &logging
  labels:
    - "scrap-logs=true"

services:
  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${RESOURCE_DB_NAME}
      POSTGRES_USER: ${RESOURCE_DB_USERNAME}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "${RESOURCE_DB_PORT}:5432"
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RESOURCE_DB_USERNAME} -d ${RESOURCE_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${SONG_DB_NAME}
      POSTGRES_USER: ${SONG_DB_USERNAME}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "${SONG_DB_PORT}:5432"
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SONG_DB_USERNAME} -d ${SONG_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  storage-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${STORAGE_DB_NAME}
      POSTGRES_USER: ${STORAGE_DB_USERNAME}
      POSTGRES_PASSWORD: ${STORAGE_DB_PASSWORD}
    ports:
      - "${STORAGE_DB_PORT}:5432"
    volumes:
      - ./init-scripts/storage-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${STORAGE_DB_USERNAME} -d ${STORAGE_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  eureka-server:
    <<: *logging
    build:
      context: ./eureka-server
    environment:
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT}
    ports:
      - "${EUREKA_SERVER_PORT}:8761"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8761/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api-gateway:
    <<: *logging
    build:
      context: ./api-gateway
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT}
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  config-server:
    <<: *logging
    build:
      context: ./config-server
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      CONFIG_SERVER_GIT_URI: ${CONFIG_SERVER_GIT_URI}
      CONFIG_SERVER_GIT_USERNAME: ${CONFIG_SERVER_GIT_USERNAME}
      CONFIG_SERVER_GIT_PASSWORD: ${CONFIG_SERVER_GIT_PASSWORD}
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT}
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8888/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  resource-processor:
    <<: *logging
    build:
      context: ./resource-processor
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      KAFKA_BOOTSTRAP_URL: ${KAFKA_BOOTSTRAP_URL}
      KAFKA_PARSING_RESOURCES_TOPIC: ${KAFKA_PARSING_RESOURCES_TOPIC}
      KAFKA_PARSING_RESOURCES_CONSUMER_GROUP: ${KAFKA_PARSING_RESOURCES_CONSUMER_GROUP}
      KAFKA_FINALIZING_RESOURCES_TOPIC: ${KAFKA_FINALIZING_RESOURCES_TOPIC}
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT}
    ports:
      - "${RESOURCE_PROCESSOR_PORT}:8086"
    depends_on:
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8086/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  resource-service:
    <<: *logging
    build:
      context: ./resource-service
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      KAFKA_BOOTSTRAP_URL: ${KAFKA_BOOTSTRAP_URL}
      KAFKA_PARSING_RESOURCES_TOPIC: ${KAFKA_PARSING_RESOURCES_TOPIC}
      KAFKA_FINALIZING_RESOURCES_TOPIC: ${KAFKA_FINALIZING_RESOURCES_TOPIC}
      KAFKA_FINALIZING_RESOURCES_CONSUMER_GROUP: ${KAFKA_FINALIZING_RESOURCES_CONSUMER_GROUP}
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT}
      OAUTH2_JWT_TOKEN_URI: ${OAUTH2_JWT_TOKEN_URI}
#      KEYCLOAK_TOKEN_URI: ${KEYCLOAK_TOKEN_URI}
#      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    ports:
      - "${RESOURCE_SERVICE_PORT}:8083"
    depends_on:
      resource-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      resource-processor:
        condition: service_healthy
      song-service:
        condition: service_healthy
      storage-service:
        condition: service_healthy
      localstack:
        condition: service_healthy
      keycloak:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8083/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  song-service:
    <<: *logging
    build:
      context: ./song-service
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT}
    ports:
      - "${SONG_SERVICE_PORT}:8084"
    depends_on:
      song-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8084/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  storage-service:
    <<: *logging
    build:
      context: ./storage-service
    environment:
      SPRING_DATASOURCE_URL: ${STORAGE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${STORAGE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${STORAGE_DB_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      MANAGEMENT_OTLP_TRACING_ENDPOINT: ${MANAGEMENT_OTLP_TRACING_ENDPOINT}
      OAUTH2_JWT_ISSUER_URI: ${OAUTH2_JWT_ISSUER_URI}
    ports:
      - "${STORAGE_SERVICE_PORT}:8087"
    depends_on:
      storage-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      keycloak:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8087/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=${AWS_S3_REGION}
      - EAGER_SERVICE_LOADING=1
      - PERSISTENCE=1
      - EDGE_PORT=${AWS_S3_PORT}
    ports:
      - '${AWS_S3_PORT}:4566'
    volumes:
      - localstack:/var/lib/localstack
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:4566/_localstack/health | grep -q '\"s3\": \"running\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      CLUSTER_ID: 'Qk9GZ3JmY3R4TnNqU1p3RQ'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1 \
          && kafka-metadata-quorum --bootstrap-server localhost:9092 describe --status | grep -Eq 'Leader:|HighWatermark:'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./config/promtail.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: '-config.file=/etc/promtail/config.yaml -config.expand-env'
    ports:
      - "9080:9080"
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.4.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3200:3200"
      - "9095:9095"

  grafana:
    image: grafana/grafana:10.3.1
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning/
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=http://localhost:3000/
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command:
      - start-dev
      - --import-realm
      - --hostname=keycloak
      - --hostname-strict=false
      - --http-enabled=true
    environment:
      KC_DB: dev-file
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_PORT: 8089
    volumes:
      - ./config/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8089:8089"

#  keycloak:
#    image: quay.io/keycloak/keycloak:26.0.7
#    container_name: keycloak
#    command:
#      - start-dev
#      - --import-realm
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - KC_HTTP_PORT=8080
#      - KC_HEALTH_ENABLED=true
#    ports:
#      - "9080:8080"
#    volumes:
#      - ./init-scripts/keycloak:/opt/keycloak/data/import
#    healthcheck:
#      test: ["CMD-SHELL", "timeout 2 sh -c '</dev/tcp/127.0.0.1/8080' || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 60s

volumes:
  localstack:
  grafana:
