create table storages (
    id bigint generated by default as identity,
    storage_type varchar(100) not null,
    bucket varchar(100) not null,
    path varchar(100) not null,
    primary key (id)
);

insert into storages
(storage_type, bucket, path)
values
('STAGING', 'resources-staging', '/staging'),
('PERMANENT', 'resources-permanent', '/permanent');
