create table storages (
    id bigint generated by default as identity,
    type varchar(100) not null,
    bucket varchar(100) not null,
    primary key (id)
);

insert into storages
(type, bucket)
values
('STAGING', 'resources-staging'),
('PERMANENT', 'resources-permanent');
