spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

spring.cloud.gateway.server.webflux.metrics.enabled=true

spring.cloud.gateway.server.webflux.httpclient.connect-timeout=2000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=5000
spring.cloud.gateway.server.webflux.routes[0].id=resource-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://resource-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/resources/**
spring.cloud.gateway.server.webflux.routes[1].id=song-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://song-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/songs/**
spring.cloud.gateway.server.webflux.routes[2].id=storage-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://storage-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/storages/**

spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.fail-fast=true

management.tracing.enabled=true
management.otlp.tracing.endpoint=${MANAGEMENT_OTLP_TRACING_ENDPOINT}
management.otlp.tracing.protocol=http
management.endpoints.web.exposure.include=health,info,metrics,prometheus,gateway,refresh
management.endpoint.gateway.access=read-only
management.endpoint.refresh.access=unrestricted
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.cloud.config=DEBUG
