{
 "title": "Spring Cloud Gateway",
 "description": "Spring Cloud Gateway Dashboard provided by: https://github.com/spring-cloud/spring-cloud-gateway",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gatewayService",
    "label": "Gateway Service",
    "query": "label_values(gateway_requests_seconds_count,job)"
   },
   {
    "name": "routeId",
    "label": "Route Id",
    "query": "label_values(gateway_requests_seconds_count,routeId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests Served",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(gateway_requests_seconds_count{job=\"api-gateway\"})"
      }
     ]
    },
    {
     "title": "Total Successful Requests Served",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=\"api-gateway\"})"
      }
     ]
    },
    {
     "title": "Total Unsuccessful Requests Served",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=\"api-gateway\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routeId",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "repeat": "routeId",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_sum{routeId=~\"$routeId\", job=\"api-gateway\"}/gateway_requests_seconds_count{routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "$routeId",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_sum{routeId=~\"$routeId\", job=\"api-gateway\"}/gateway_requests_seconds_count{routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "$routeId",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_sum{routeId=~\"$routeId\", job=\"api-gateway\"}/gateway_requests_seconds_count{routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "$routeId",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_sum{routeId=~\"$routeId\", job=\"api-gateway\"}/gateway_requests_seconds_count{routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Successful API Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routeId Success API Gateway Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "repeat": "routeId",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ job }} / {{ routeUri }}"
      }
     ]
    },
    {
     "title": "$routeId Success API Gateway Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ job }} / {{ routeUri }}"
      }
     ]
    },
    {
     "title": "$routeId Success API Gateway Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ job }} / {{ routeUri }}"
      }
     ]
    },
    {
     "title": "$routeId Success API Gateway Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ job }} / {{ routeUri }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unsuccessful API Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routeId Unsuccessful GW Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "repeat": "routeId",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"$routeId\", job=\"api-gateway\"}",
       "legendFormat": "{{ job }} / {{ routeUri }}"
      }
     ]
    }
   ]
  },
  {
   "title": "API / HTTP Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routeId",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
     "repeat": "routeId",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gateway_requests_seconds_count{routeId=~\"$routeId\", job=\"api-gateway\"}) by (job, status)",
       "legendFormat": "{{ job }} / {{ status }}"
      }
     ]
    },
    {
     "title": "$routeId",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gateway_requests_seconds_count{routeId=~\"$routeId\", job=\"api-gateway\"}) by (job, status)",
       "legendFormat": "{{ job }} / {{ status }}"
      }
     ]
    },
    {
     "title": "$routeId",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gateway_requests_seconds_count{routeId=~\"$routeId\", job=\"api-gateway\"}) by (job, status)",
       "legendFormat": "{{ job }} / {{ status }}"
      }
     ]
    },
    {
     "title": "$routeId",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gateway_requests_seconds_count{routeId=~\"$routeId\", job=\"api-gateway\"}) by (job, status)",
       "legendFormat": "{{ job }} / {{ status }}"
      }
     ]
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"api-gateway\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"api-gateway\"}) by (job, instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{job=\"api-gateway\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total/jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}