auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

memberlist:
  bind_port: 7946
  # Optional if name resolution is flaky:
  # advertise_addr: 172.20.0.10

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  lifecycler:
    ring:
      replication_factor: 1
#    interface_names: [ "eth0" ]
  partition_ring:
    # instance_addr and interface_names are NOT allowed here
    kvstore:
      store: memberlist

live_store:
  ring:
#    instance_addr: tempo
    kvstore:
      store: memberlist

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks