spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always

management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

logging.pattern.level=trace_id=%mdc{trace_id:-0} %5p
