spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.tracing.enabled=true
management.otlp.tracing.endpoint=${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
management.otlp.tracing.protocol=http
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.access=read-only
management.endpoint.prometheus.access=read-only
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
