spring.application.name=config-server
server.port=8888

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

spring.cloud.config.server.git.uri=${CONFIG_SERVER_GIT_URI:https://github.com/aliakh/microservices-fundamentals-config-server.git}
spring.cloud.config.server.git.username=${CONFIG_SERVER_GIT_USERNAME:aliakh}
spring.cloud.config.server.git.password=${CONFIG_SERVER_GIT_PASSWORD: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
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths={application}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.timeout=10
spring.cloud.config.server.git.refresh-rate=10

management.tracing.enabled=true
management.otlp.tracing.endpoint=${MANAGEMENT_OTLP_TRACING_ENDPOINT}
management.otlp.tracing.protocol=http
management.endpoints.web.exposure.include=health,info,refresh,metrics,prometheus
management.endpoint.refresh.access=unrestricted
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

logging.level.org.springframework.cloud.config=DEBUG
